In [37]:
import pandas as pd
import numpy as np

In [38]:
ml_df = pd.read_csv('datasets/final_crop_dataset4.csv')

In [39]:
ml_df

,County,Crop,AvgTemp,Rainfall,Humidity,Soil_pH,Price
0,baringo,Wheat,22.642890,890.25,60.413753,6.800000,58.000000
1,baringo,Wheat,22.819562,1120.88,62.320082,6.800000,69.083333
2,bomet,Wheat,19.128041,805.47,66.778849,6.766667,90.487500
3,bomet,Dry Maize,18.072254,1754.47,78.862814,6.766667,41.539792
4,bomet,Dry Onions,18.072254,1754.47,78.862814,6.766667,169.509434
...,...,...,...,...,...,...,...
226,vihiga,Tomatoes,20.814577,3042.99,76.261885,5.500000,75.090414
227,wajir,Dry Onions,29.917063,321.84,54.807951,7.600000,140.149118
228,wajir,Kales/Sukuma Wiki,29.917063,321.84,54.807951,7.600000,69.768623
229,wajir,Tomatoes,29.917063,321.84,54.807951,7.600000,55.000000
230,west pokot,Wheat,21.605945,1405.77,66.959096,6.200000,135.000000

In [40]:
from sklearn.preprocessing import LabelEncoder

le_county = LabelEncoder()
ml_df["County"] = le_county.fit_transform(ml_df["County"])

le_crop = LabelEncoder()
ml_df["Crop"] = le_crop.fit_transform(ml_df["Crop"])

In [41]:
ml_df

     County  Crop    AvgTemp  Rainfall   Humidity   Soil_pH       Price
0         0     7  22.642890    890.25  60.413753  6.800000   58.000000
1         0     7  22.819562   1120.88  62.320082  6.800000   69.083333
2         1     7  19.128041    805.47  66.778849  6.766667   90.487500
3         1     1  18.072254   1754.47  78.862814  6.766667   41.539792
4         1     2  18.072254   1754.47  78.862814  6.766667  169.509434
..      ...   ...        ...       ...        ...       ...         ...
226      43     6  20.814577   3042.99  76.261885  5.500000   75.090414
227      44     2  29.917063    321.84  54.807951  7.600000  140.149118
228      44     3  29.917063    321.84  54.807951  7.600000   69.768623
229      44     6  29.917063    321.84  54.807951  7.600000   55.000000
230      45     7  21.605945   1405.77  66.959096  6.200000  135.000000

[231 rows x 7 columns]

In [42]:
# split features and target
X = ml_df.drop("Crop", axis=1)
y = ml_df["Crop"]

In [43]:
# train test split
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

In [44]:
# train the model
from sklearn.ensemble import RandomForestClassifier

model = RandomForestClassifier(
    n_estimators=200,
    random_state=42
)

model.fit(X_train, y_train)

RandomForestClassifier(n_estimators=200, random_state=42)

In [46]:
# evaluate model
from sklearn.metrics import accuracy_score

pred = model.predict(X_test)

accuracy = accuracy_score(y_test, pred)

print("Accuracy:", accuracy)

Accuracy: 0.2978723404255319

In [47]:
# predict crop
new_data = [[
    32,
    30,
    400,
    50,
    6.0,
    45
]]

prediction = model.predict(new_data)

recommended_crop = le_crop.inverse_transform(prediction)

county = le_county.inverse_transform([new_data[0][0]])

print("Recommended crop:", recommended_crop[0])
print("County:", county[0])

Recommended crop: Tomatoes
County: nyamira

/home/ushindi/AI/models/venv/lib/python3.12/site-packages/sklearn/utils/validation.py:2691: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(

In [19]:
ml_df["Crop"].value_counts()

Crop
7    84
3    27
1    24
2    24
6    24
4    23
5    20
0     5
Name: count, dtype: int64

In [48]:
for i, crop in enumerate(le_crop.classes_):
    print(i, crop)

0 Coffee
1 Dry Maize
2 Dry Onions
3 Kales/Sukuma Wiki
4 Rice
5 Tea
6 Tomatoes
7 Wheat

In [49]:
X.isna().sum()

County      0
AvgTemp     0
Rainfall    0
Humidity    0
Soil_pH     0
Price       0
dtype: int64

In [52]:
from imblearn.over_sampling import SMOTE

smote = SMOTE(k_neighbors=3, random_state=42)

X_resampled, y_resampled = smote.fit_resample(X, y)

In [53]:
from sklearn.ensemble import RandomForestClassifier

model = RandomForestClassifier(
    n_estimators=200,
    random_state=42
)

model.fit(X_resampled, y_resampled)

RandomForestClassifier(n_estimators=200, random_state=42)

In [55]:
# evaluate model
from sklearn.metrics import accuracy_score

pred = model.predict(X_test)

accuracy = accuracy_score(y_test, pred)

print("Accuracy:", accuracy)

Accuracy: 0.9574468085106383

In [56]:
# predict crop
new_data = [[
    5,
    18,
    700,
    60,
    6.5,
    65
]]

prediction = model.predict(new_data)

recommended_crop = le_crop.inverse_transform(prediction)

county = le_county.inverse_transform([new_data[0][0]])

print("Recommended crop:", recommended_crop[0])
print("County:", county[0])

Recommended crop: Tomatoes
County: nyamira

/home/ushindi/AI/models/venv/lib/python3.12/site-packages/sklearn/utils/validation.py:2691: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(